# Generated by Django 5.2 on 2025-05-13 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('payments', '0003_gameorder_gameordertype_repairorder_repairordertype'),
        ('storage', '0002_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.orderproduct'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='payments.order'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Success', 'موفق'), ('Suspended', 'تعلیق'), ('Cancelled', 'کنسل شده'), ('Failed', 'ناموفق')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gameorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='gameorder',
            name='order_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.ordertype'),
        ),
        migrations.AddField(
            model_name='gameorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.orderproduct'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='game_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_order', to='payments.gameorder'),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='order_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.ordertype'),
        ),
        migrations.AddField(
            model_name='repairorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.orderproduct'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='repair_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_order', to='payments.repairorder'),
        ),
    ]
