# Generated by Django 5.2 on 2025-05-18 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_gameorder_is_deleted_gameordertype_is_deleted_and_more'),
        ('storage', '0003_remove_orderproduct_owner_game_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.customerconsole'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.customerconsole'),
        ),
        migrations.AlterField(
            model_name='repairorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.customerconsole'),
        ),
    ]
