# Generated by Django 5.2.3 on 2025-06-12 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_businesscustomer_user_alter_customer_user'),
        ('payments', '0007_courseorder_transaction_course_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorder',
            name='user',
        ),
        migrations.AddField(
            model_name='courseorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='gameorder',
            name='order_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.gameordertype'),
        ),
    ]
