# Generated by Django 5.2.3 on 2025-06-18 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_transaction_course_order_and_more'),
        ('storage', '0008_game_units_sold_product_units_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.product'),
        ),
    ]
