# Generated by Django 5.2.3 on 2025-06-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_order_description'),
        ('storage', '0008_game_units_sold_product_units_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameorder',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='orders', to='storage.game'),
        ),
    ]
