# Generated by Django 5.2.3 on 2025-07-01 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employeetask_is_deleted'),
        ('payments', '0012_order_description'),
        ('storage', '0008_game_units_sold_product_units_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameorder',
            name='account_setter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_setter', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='gameorder',
            name='data_uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_uploader', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='gameorder',
            name='games',
            field=models.ManyToManyField(blank=True, to='storage.game'),
        ),
        migrations.AddField(
            model_name='gameorder',
            name='status',
            field=models.CharField(choices=[('payed', 'پرداخت شده'), ('in_progress', 'در حال انجام'), ('data', 'دیتا ریختن'), ('done', 'اتمام')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gameordertype',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True),
        ),
    ]
