# Generated by Django 5.2.3 on 2025-07-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_gameorder_account_setter_gameorder_data_uploader_and_more'),
        ('storage', '0009_sonyaccount_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameorder',
            name='sony_accounts',
            field=models.ManyToManyField(blank=True, to='storage.sonyaccount'),
        ),
        migrations.AlterField(
            model_name='gameorder',
            name='status',
            field=models.CharField(choices=[('waiting', 'در انتظار پرداخت'), ('payed', 'پرداخت شده'), ('in_progress', 'در حال انجام'), ('data', 'دیتا ریختن'), ('done', 'اتمام'), ('delivered', 'تحویل شده')], max_length=50, null=True),
        ),
    ]
