# Generated by Django 5.2.3 on 2025-07-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_gameorder_games'),
        ('payments', '0014_gameorder_sony_accounts_alter_gameorder_status'),
    ]

    operations = [
    ]
