# Generated by Django 5.2.3 on 2025-07-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_merge_20250707_1501'),
        ('storage', '0010_sonyaccount_is_owned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameorder',
            name='games',
            field=models.ManyToManyField(blank=True, to='storage.game'),
        ),
    ]
