# Generated by Django 5.2.3 on 2025-07-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_alter_gameorder_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payer_str',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_str',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
