# Generated by Django 5.2 on 2025-05-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_gameorder_product_alter_order_product_and_more'),
        ('storage', '0003_remove_orderproduct_owner_game_is_deleted_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
