# Generated by Django 5.2 on 2025-05-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_delete_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sonyaccountgame',
            name='added_at',
        ),
    ]
