# Generated by Django 5.2 on 2025-06-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_remove_sonyaccountgame_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_trend',
            field=models.BooleanField(default=False),
        ),
    ]
