# Generated by Django 5.2.3 on 2025-07-02 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_user'),
        ('storage', '0008_game_units_sold_product_units_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonyaccount',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
    ]
