# Generated by Django 5.2.3 on 2025-07-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_sonyaccount_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonyaccount',
            name='is_owned',
            field=models.BooleanField(default=False),
        ),
    ]
