# Generated by Django 5.2.3 on 2025-07-07 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_rename_is_access_to_accounts_employee_has_access_to_accounts_and_more'),
        ('storage', '0010_sonyaccount_is_owned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonyaccount',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_accounts', to='employees.employee'),
        ),
    ]
