# Generated by Django 5.2 on 2025-05-24 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_is_deleted_employeerole_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerole',
            name='type',
            field=models.CharField(blank=True, choices=[('operational', 'عملیاتی'), ('in organ', 'درون سازمانی')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('Personal', 'شخصی'), ('Organize', 'سازمانی')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('status', models.CharField(choices=[('planed', 'برنامه ریزی شده'), ('in progress', 'در حال انجام'), ('done', 'انجام شده')], max_length=20)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
