# Generated by Django 5.2.3 on 2025-07-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_employee_role_employee_is_access_to_accounts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_access_to_accounts',
            new_name='has_access_to_accounts',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='is_access_to_calls',
            new_name='has_access_to_calls',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='is_access_to_chat',
            new_name='has_access_to_chat',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='is_access_to_customers',
            new_name='has_access_to_customers',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='is_access_to_orders',
            new_name='has_access_to_orders',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='is_access_to_products',
            new_name='has_access_to_products',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='is_access_to_transactions',
            new_name='has_access_to_transactions',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='income_type',
        ),
        migrations.AddField(
            model_name='employee',
            name='commission_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='has_commission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_account_setter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_data_uploader',
            field=models.BooleanField(default=False),
        ),
    ]
