# Generated by Django 5.2.3 on 2025-07-11 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_rename_is_access_to_accounts_employee_has_access_to_accounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetask',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
