# Generated by Django 5.2.3 on 2025-07-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_employeetask_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_access_to_game_order',
            field=models.BooleanField(default=False),
        ),
    ]
