# Generated by Django 5.2 on 2025-05-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_apikey_customuser_ia_deleted_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='ia_deleted',
            new_name='is_deleted',
        ),
    ]
