# Generated by Django 5.2 on 2025-05-26 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_ia_deleted_customuser_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('access', models.CharField(choices=[('1', '1')], max_length=1, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
