# Generated by Django 5.2 on 2025-05-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_deleted'),
        ('accounts', '0005_mainmanager'),
    ]

    operations = [
    ]
