# Generated by Django 5.2 on 2025-05-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_blogpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
