# Generated by Django 5.2 on 2025-05-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_contactus_created_at_contactus_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='address',
            field=models.CharField(max_length=700),
        ),
    ]
