# Generated by Django 5.2 on 2025-05-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_blogtag_alter_blogcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='blogtag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
