# Generated by Django 5.2 on 2025-05-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_blogcategory_options_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='عنوان'),
        ),
    ]
