# Generated by Django 5.2.3 on 2025-06-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_homebanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseOrder',
        ),
    ]
