# Generated by Django 5.2.3 on 2025-06-12 15:27

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_delete_courseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='phone',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
