# Generated by Django 5.2.3 on 2025-07-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
