# Generated by Django 5.2.3 on 2025-07-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_cart_user_alter_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='BlogTag',
        ),
    ]
