# Generated by Django 5.2 on 2025-05-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscustomer',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='business/license/'),
        ),
    ]
