# Generated by Django 5.2 on 2025-05-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_businesscustomer_license'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessCustomer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
